# Generated by Django 5.0.7 on 2024-08-12 07:46

import apps.shop.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.shop.models.dtime)),
                ('names', models.CharField(max_length=255)),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('expiry', models.DateField()),
                ('deleted', models.BooleanField(default=False)),
                ('lastEdited', models.DateTimeField(default=None, null=True)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pro_registrar', to=settings.AUTH_USER_MODEL)),
                ('editedBy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pro_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
