# Generated by Django 5.0.7 on 2024-08-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.TextField(default=None, null=True),
        ),
    ]
