# Generated by Django 5.0.7 on 2024-08-22 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
