# Generated by Django 5.0.7 on 2024-08-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry',
            field=models.DateField(default=None, null=True),
        ),
    ]
